### ISSUE TITLE
Capacity of rust vec is lost in rust boundary when created and reserved in c++ boundary

### ISSUE THREAD

**Issue by lucamuscat** [dtolnay/cxx#1278]
Hi!

When creating a `rust::Vec` and reserving capacity (via `vec.reserve`) inside of the c++ boundary, the rust boundary's `Vec::capacity` method fails to return the correct capacity (returns only zero). 

I created a small MVP of this bug, adapted from the demo code of this project, where a `rust::Vec<uint8t_t> vec` is created, and `vec.reserve(10)` is called. The bug may be observed by comparing the capacity of the `Vec` inside of c++, and the capacity of that same Vec inside of the rust boundary.

# Output
## Actual
```
© C++: Capacity of vec 10
🦀 Rust: Capacity of vec: 0
```
## Expected
```
© C++: Capacity of vec 10
🦀 Rust: Capacity of vec: 10
```

# MVP
```cpp
// demo/include/blobstore.h
#pragma once
#include "rust/cxx.h"
#include <memory>

void call_print_capacity();
```

```cpp
// demo/src/blobstore.cc
#include "demo/include/blobstore.h"
#include "demo/src/main.rs.h"
#include <iostream>

void call_print_capacity() {
    rust::Vec<uint8_t> vec;
    vec.reserve(10);
    std::cout << "© C++: Capacity of vec " << vec.capacity() << std::endl;
    // Pass `vec` inside the rust boundary, where its capacity will be printed 
    ::ffi::print_capacity(vec);
}
```

```rust
// demo/src/main.rs
use ffi::call_print_capacity;

#[cxx::bridge(namespace = "ffi")]
mod ffi {
    // Rust types and signatures exposed to C++.
    extern "Rust" {
        fn print_capacity(blob: Vec<u8>);
    }

    // C++ types and signatures exposed to Rust.
    #[namespace = ""]
    unsafe extern "C++" {
        include!("demo/include/blobstore.h");
        fn call_print_capacity();
    }
}

    
fn print_capacity(blob: Vec<u8>) {
    println!("🦀 Rust: Capacity of vec: {}", blob.capacity());
}

fn main() {
    // Found in the c++ boundary, creates a rust::Vec, reserves a capacity of 10, prints said capacity
    // then prints the capacity the same vec inside of rust.
    call_print_capacity();
}
```

```toml
# demo/Cargo.toml
[package]
name = "demo"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
description = "Toy project from https://github.com/dtolnay/cxx"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false
repository = "https://github.com/dtolnay/cxx"

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"
```

# Machine Environment Data
## Cargo version
`cargo 1.72.1 (103a7ff2e 2023-08-15)`

## Truncated output of `hostnamectl`
```
Virtualization: microsoft
  Operating System: Ubuntu 20.04.6 LTS
            Kernel: Linux 5.15.0-1049-azure
      Architecture: x86-64
```

I would like to thank all the contributors who have created this great project :) 

If you require any more information from me, kindly let me know.

Regards,
Luca
