### ISSUE TITLE
no-std compilation issue

### ISSUE THREAD

**Issue by libesz** [dtolnay/cxx#1286]
Hey!
 I am trying to use CXX to compile Rust and C++ to an embedded arm platform (STM32F4). I found earlier discussions and PRs about this topic and as I understood it should work, so maybe I am still doing something wrong.

Using this to avoid std usage:
```toml
cxx = { version = "1.0.110", default-features = false, features = ["alloc"] }
```

and the build still gives me this:
```
rust-lld: error: unable to find library -lstdc++
```

I've put the demo project here: https://github.com/libesz/temp-rust-cxx-demo

**Comment by dtolnay** [comment]
The `-lstdc++` comes from link-cplusplus. You can turn it off like this in Cargo.toml:

```toml
[dependencies]
link-cplusplus = { version = "1", features = ["nothing"] }
```
