### ISSUE TITLE
How to include lib.rs.h from another crate

### ISSUE THREAD

**Issue by Earthson** [dtolnay/cxx#917]
```
- crate-a: // cxx based crate
    - src/lib.rs
- crate-b: // another cxx based crate
    - src/lib.rs
    - src/test.cpp // #include crate-a/src/lib.rs.h FAILED
```

#### dependencies of crate-b

```toml
[dependencies]
crate-a = { path = "../crate-a" }
```
